### ISSUE TITLE
[BUG] Error On Creating new save

### ISSUE THREAD

**Issue by Secondyou** [dimankiev/dhackos#12]
**Describe the bug**

**To Reproduce**
1. Start A Game
2. Make a new save (if you installed first time)
3. crash by module is uncallable

**Expected behavior**
Game Correctly Create Saves
**Screenshots**
I Only Has Error Here
```
Traceback (most recent call last):                        File "/data/data/com.termux/files/home/dhackos/dhackos.py", line 767, in <module>
    newGame()
  File "/data/data/com.termux/files/home/dhackos/dhackos.py", line 257, in newGame
    for i in progressbar.progressbar(range(100)): time.sleep(0.1)                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```
**Desktop (please complete the following information):**
 - OS: Android
 - Python version 3.11.6
 - Version Lastest

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10
 - OS: PixelExp 13
 - Version : Lastest

**Additional context**

**Comment by Secondyou** [comment]
installed wrong version of progress bar now fixed
